// The animals that live on the desktop. Artwork is in assets/animals/<id>.svg (Noto Emoji, Apache 2.0).
// size: height in pixels. gait: how it moves (walk, hop, waddle, slither, crawl, scuttle, fly, hang).
window.ANIMALS = [
  {
    id: "cat",
    name: "cat",
    latin: "Felis catus",
    size: 30,
    gait: "walk",
    lives: "homes all over the world",
    eats: "meat. cats are obligate carnivores",
    fact: "cats can't taste sweet things. the gene for the sweet taste receptor doesn't work in them.",
  },
  {
    id: "black-cat",
    name: "black cat",
    latin: "Felis catus",
    size: 30,
    gait: "walk",
    lives: "homes all over the world",
    eats: "meat",
    fact: "black fur can 'rust' to a reddish brown after lots of sun. in japan and scotland a black cat means good luck.",
  },
  {
    id: "dog",
    name: "dog",
    latin: "Canis familiaris",
    size: 32,
    gait: "walk",
    lives: "wherever people are. dogs were domesticated from wolves at least 15,000 years ago",
    eats: "mostly meat, but they're omnivores",
    fact: "every dog's nose print is unique, like a human fingerprint.",
  },
  {
    id: "poodle",
    name: "poodle",
    latin: "Canis familiaris",
    size: 32,
    gait: "walk",
    lives: "homes. the breed started in germany as a water retriever",
    eats: "dog food, ideally",
    fact: "the fancy clip started out practical: shaved for swimming, with fur left to keep the joints and chest warm.",
  },
  {
    id: "rabbit",
    name: "rabbit",
    latin: "Oryctolagus cuniculus",
    size: 30,
    gait: "hop",
    lives: "meadows and burrows called warrens, plus a lot of homes",
    eats: "grass, hay and leafy greens",
    fact: "a happy rabbit leaps and twists in the air. it's called a binky. their teeth never stop growing.",
  },
  {
    id: "mouse",
    name: "house mouse",
    latin: "Mus musculus",
    size: 22,
    gait: "walk",
    lives: "near people, on every continent except antarctica",
    eats: "seeds, grain and almost anything else",
    fact: "male mice sing ultrasonic songs to court females, too high for us to hear.",
  },
  {
    id: "chipmunk",
    name: "eastern chipmunk",
    latin: "Tamias striatus",
    size: 26,
    gait: "walk",
    lives: "forests of eastern north america",
    eats: "nuts, seeds, berries and insects",
    fact: "their cheek pouches can stretch to about three times the size of their head.",
  },
  {
    id: "hedgehog",
    name: "european hedgehog",
    latin: "Erinaceus europaeus",
    size: 26,
    gait: "walk",
    lives: "gardens, hedges and woodland edges across europe",
    eats: "beetles, worms and slugs",
    fact: "an adult has around 5,000 to 7,000 spines and rolls into a ball when it's scared.",
  },
  {
    id: "otter",
    name: "sea otter",
    latin: "Enhydra lutris",
    size: 32,
    gait: "walk",
    lives: "coasts of the north pacific",
    eats: "sea urchins, crabs and clams",
    fact: "they have the densest fur of any animal, and hold paws while they sleep so they don't drift apart.",
  },
  {
    id: "sloth",
    name: "brown-throated sloth",
    latin: "Bradypus variegatus",
    size: 46,
    gait: "hang",
    lives: "rainforests of central and south america",
    eats: "leaves",
    fact: "they climb down about once a week, just to go to the bathroom. algae grows in their fur.",
  },
  {
    id: "skunk",
    name: "striped skunk",
    latin: "Mephitis mephitis",
    size: 30,
    gait: "walk",
    lives: "north america, from canada to mexico",
    eats: "insects, grubs, small animals and fruit",
    fact: "before spraying it warns you: it stamps its feet, hisses and lifts its tail. the spray reaches about 3 metres.",
  },
  {
    id: "badger",
    name: "european badger",
    latin: "Meles meles",
    size: 30,
    gait: "walk",
    lives: "woodland across europe, in underground tunnels called setts",
    eats: "earthworms, mostly",
    fact: "some setts are used by badger families for decades, even centuries, and keep growing.",
  },
  {
    id: "beaver",
    name: "north american beaver",
    latin: "Castor canadensis",
    size: 32,
    gait: "walk",
    lives: "rivers, lakes and ponds",
    eats: "bark, twigs and water plants",
    fact: "their front teeth are orange because the enamel contains iron, which makes it tougher.",
  },
  {
    id: "kangaroo",
    name: "red kangaroo",
    latin: "Osphranter rufus",
    size: 40,
    gait: "hop",
    lives: "dry grassland and desert across australia",
    eats: "grass",
    fact: "the biggest kangaroo. it can cover around 8 metres in one hop, and a newborn joey is about the size of a jellybean.",
  },
  {
    id: "deer",
    name: "white-tailed deer",
    latin: "Odocoileus virginianus",
    size: 40,
    gait: "walk",
    lives: "forests and fields from canada to south america",
    eats: "leaves, twigs, acorns and grass",
    fact: "males grow a new set of antlers every year. antler is one of the fastest-growing tissues of any mammal.",
  },
  {
    id: "horse",
    name: "horse",
    latin: "Equus caballus",
    size: 44,
    gait: "walk",
    lives: "farms and fields worldwide, plus wild herds",
    eats: "grass and hay",
    fact: "a 'stay apparatus' locks their legs so they can doze standing up. for deep sleep they still lie down.",
  },
  {
    id: "zebra",
    name: "plains zebra",
    latin: "Equus quagga",
    size: 42,
    gait: "walk",
    lives: "grasslands of eastern and southern africa",
    eats: "grass",
    fact: "no two zebras have the same stripes, and studies suggest the stripes help keep biting flies away.",
  },
  {
    id: "giraffe",
    name: "giraffe",
    latin: "Giraffa camelopardalis",
    size: 54,
    gait: "walk",
    lives: "african savanna",
    eats: "leaves, especially acacia",
    fact: "a giraffe's neck has seven bones, the same number as yours. each one can be about 25 cm long.",
  },
  {
    id: "pig",
    name: "pig",
    latin: "Sus domesticus",
    size: 34,
    gait: "walk",
    lives: "farms worldwide",
    eats: "almost anything. pigs are omnivores",
    fact: "pigs barely sweat, so they roll in mud to cool off. they've even learned simple video games with a joystick.",
  },
  {
    id: "cow",
    name: "cow",
    latin: "Bos taurus",
    size: 40,
    gait: "walk",
    lives: "farms and fields worldwide",
    eats: "grass, which they bring back up and chew again as cud",
    fact: "cows have best friends. one study found they're calmer when their favourite cow is with them.",
  },
  {
    id: "ewe",
    name: "sheep",
    latin: "Ovis aries",
    size: 34,
    gait: "walk",
    lives: "farms and hills worldwide",
    eats: "grass and clover",
    fact: "sheep can remember the faces of at least 50 other sheep for over two years.",
  },
  {
    id: "goat",
    name: "goat",
    latin: "Capra hircus",
    size: 34,
    gait: "walk",
    lives: "farms, hills and mountains worldwide",
    eats: "shrubs, weeds and leaves. not tin cans",
    fact: "their rectangular pupils give them a wide view all around, to watch for predators.",
  },
  {
    id: "llama",
    name: "llama",
    latin: "Lama glama",
    size: 42,
    gait: "walk",
    lives: "the andes of south america, and farms worldwide",
    eats: "grass and hay",
    fact: "llamas hum to each other, and farmers keep them as guards for sheep.",
  },
  {
    id: "two-hump-camel",
    name: "bactrian camel",
    latin: "Camelus bactrianus",
    size: 46,
    gait: "walk",
    lives: "the cold deserts of central asia, like the gobi",
    eats: "almost any plant, even thorny ones",
    fact: "the humps store fat, not water. a thirsty camel can drink over 100 litres in under 15 minutes.",
  },
  {
    id: "elephant",
    name: "asian elephant",
    latin: "Elephas maximus",
    size: 50,
    gait: "walk",
    lives: "forests and grasslands of south and southeast asia",
    eats: "grass, bark, roots and fruit, up to 150 kg a day",
    fact: "the trunk has tens of thousands of muscles, and it's precise enough to pick up a single peanut.",
  },
  {
    id: "rhinoceros",
    name: "white rhinoceros",
    latin: "Ceratotherium simum",
    size: 44,
    gait: "walk",
    lives: "grasslands of southern africa",
    eats: "grass",
    fact: "a rhino's horn is made of keratin, the same stuff as your hair and fingernails.",
  },
  {
    id: "hippopotamus",
    name: "hippopotamus",
    latin: "Hippopotamus amphibius",
    size: 42,
    gait: "walk",
    lives: "rivers and lakes in africa",
    eats: "grass, grazed at night",
    fact: "they make their own sunscreen: a reddish, oily sweat that blocks sunlight and fights germs.",
  },
  {
    id: "tiger",
    name: "tiger",
    latin: "Panthera tigris",
    size: 40,
    gait: "walk",
    lives: "forests and grasslands of asia",
    eats: "deer, wild pigs and other large animals",
    fact: "every tiger's stripes are unique, and they're on its skin too, not just the fur.",
  },
  {
    id: "leopard",
    name: "leopard",
    latin: "Panthera pardus",
    size: 38,
    gait: "walk",
    lives: "africa and asia, from rainforest to desert",
    eats: "antelope, monkeys, and almost anything it can catch",
    fact: "they drag their kills up into trees to keep them away from lions and hyenas.",
  },
  {
    id: "gorilla",
    name: "western gorilla",
    latin: "Gorilla gorilla",
    size: 42,
    gait: "walk",
    lives: "rainforests of central africa",
    eats: "leaves, stems and fruit",
    fact: "gorillas build a fresh nest of leaves to sleep in every night.",
  },
  {
    id: "orangutan",
    name: "bornean orangutan",
    latin: "Pongo pygmaeus",
    size: 38,
    gait: "walk",
    lives: "rainforests of borneo",
    eats: "fruit, especially figs, plus leaves and bark",
    fact: "babies stay with their mothers for about 7 years, one of the longest childhoods of any animal.",
  },
  {
    id: "mammoth",
    name: "woolly mammoth",
    latin: "Mammuthus primigenius",
    size: 50,
    gait: "walk",
    lives: "extinct. it roamed the cold steppes of the northern hemisphere",
    eats: "grasses and other tundra plants",
    fact: "the last ones lived on wrangel island until about 4,000 years ago, after the great pyramid was built.",
  },
  {
    id: "penguin",
    name: "emperor penguin",
    latin: "Aptenodytes forsteri",
    size: 32,
    gait: "waddle",
    lives: "the sea ice around antarctica",
    eats: "fish, krill and squid",
    fact: "dads keep the egg warm on their feet through the antarctic winter, for about two months without eating.",
  },
  {
    id: "duck",
    name: "mallard",
    latin: "Anas platyrhynchos",
    size: 30,
    gait: "waddle",
    lives: "ponds, lakes and parks across the northern hemisphere",
    eats: "plants, seeds, insects and snails",
    fact: "ducklings imprint on the first moving thing they see after hatching, usually their mom.",
  },
  {
    id: "flamingo",
    name: "american flamingo",
    latin: "Phoenicopterus ruber",
    size: 42,
    gait: "waddle",
    lives: "salty lagoons and mudflats around the caribbean",
    eats: "algae, shrimp and other tiny crustaceans",
    fact: "they're pink because of pigments in what they eat. chicks hatch grey.",
  },
  {
    id: "peacock",
    name: "indian peafowl",
    latin: "Pavo cristatus",
    size: 40,
    gait: "waddle",
    lives: "forests and farmland in india and sri lanka",
    eats: "seeds, insects, plants, even small snakes",
    fact: "only the males, peacocks, have the long train. females are peahens, and together they're peafowl.",
  },
  {
    id: "rooster",
    name: "rooster",
    latin: "Gallus gallus domesticus",
    size: 34,
    gait: "waddle",
    lives: "farms and backyards worldwide",
    eats: "seeds, grain and bugs",
    fact: "roosters crow before dawn because of an internal clock, not just because they see the light.",
  },
  {
    id: "dodo",
    name: "dodo",
    latin: "Raphus cucullatus",
    size: 34,
    gait: "waddle",
    lives: "extinct since the late 1600s. it lived only on the island of mauritius",
    eats: "probably fruit, seeds and nuts",
    fact: "its closest living relative is the nicobar pigeon.",
  },
  {
    id: "goose",
    name: "domestic goose",
    latin: "Anser anser domesticus",
    size: 34,
    gait: "waddle",
    lives: "farms and ponds worldwide",
    eats: "grass, grain and water plants",
    fact: "geese often pair for life, and they make famously good guards: they honk at strangers.",
  },
  {
    id: "baby-chick",
    name: "chick",
    latin: "Gallus gallus domesticus",
    size: 22,
    gait: "waddle",
    lives: "farms and backyards worldwide",
    eats: "seeds, grain and bugs",
    fact: "chicks start peeping to their mother from inside the egg, a day or so before they hatch.",
  },
  {
    id: "cricket",
    name: "house cricket",
    latin: "Acheta domesticus",
    size: 22,
    gait: "hop",
    lives: "warm places worldwide, often near people",
    eats: "plants, insects and crumbs",
    fact: "only males chirp, by rubbing their wings together, and they chirp faster when it's warmer.",
  },
  {
    id: "turtle",
    name: "turtle",
    latin: "Testudines",
    size: 28,
    gait: "crawl",
    lives: "every continent except antarctica, on land and in water",
    eats: "plants, insects or fish, depending on the species",
    fact: "the shell is part of the skeleton, fused to the ribs and spine, so a turtle can't climb out of it.",
  },
  {
    id: "snake",
    name: "snake",
    latin: "Serpentes",
    size: 30,
    gait: "slither",
    lives: "every continent except antarctica",
    eats: "whole animals. snakes can't chew",
    fact: "they smell with their tongues: the fork collects scents and delivers them to an organ in the roof of the mouth.",
  },
  {
    id: "crab",
    name: "crab",
    latin: "Brachyura",
    size: 28,
    gait: "scuttle",
    lives: "oceans, beaches, rivers and even dry land",
    eats: "algae, worms, clams and leftovers",
    fact: "most crabs walk sideways because their legs bend outward, so sideways is the quickest way to go.",
  },
  {
    id: "snail",
    name: "garden snail",
    latin: "Cornu aspersum",
    size: 24,
    gait: "crawl",
    lives: "gardens and woods. it started out around the mediterranean",
    eats: "leaves, flowers and algae",
    fact: "its tongue, called a radula, is covered in thousands of tiny teeth.",
  },
  {
    id: "t-rex",
    name: "tyrannosaurus rex",
    latin: "Tyrannosaurus rex",
    size: 50,
    gait: "walk",
    lives: "extinct for 66 million years. it lived in western north america",
    eats: "other dinosaurs",
    fact: "t. rex lived closer in time to us than to stegosaurus.",
  },
  {
    id: "bat",
    name: "little brown bat",
    latin: "Myotis lucifugus",
    size: 34,
    gait: "fly",
    lives: "forests near water across north america",
    eats: "insects: mosquitoes, moths and beetles",
    fact: "bats are the only mammals that can truly fly. this one can eat hundreds of insects in a night.",
  },
  {
    id: "parrot",
    name: "parrot",
    latin: "Psittaciformes",
    size: 32,
    gait: "fly",
    lives: "warm forests around the world, mostly in the tropics",
    eats: "seeds, nuts, fruit and flowers",
    fact: "many parrots favour one foot, like being left- or right-handed. some live for more than 60 years.",
  },
  {
    id: "owl",
    name: "owl",
    latin: "Strigiformes",
    size: 32,
    gait: "fly",
    lives: "almost everywhere, from forests to deserts to the arctic",
    eats: "mice, voles, insects and small birds",
    fact: "owls can't move their eyes, so they turn their heads instead, up to about 270 degrees.",
  },
  {
    id: "dove",
    name: "dove",
    latin: "Columbidae",
    size: 30,
    gait: "fly",
    lives: "nearly everywhere",
    eats: "seeds and grain",
    fact: "doves and pigeons feed their chicks 'crop milk', and both parents make it.",
  },
  {
    id: "honeybee",
    name: "western honey bee",
    latin: "Apis mellifera",
    size: 22,
    gait: "fly",
    lives: "hives on every continent except antarctica",
    eats: "nectar and pollen",
    fact: "bees tell their hive where the flowers are with a 'waggle dance' that points the way.",
  },
  {
    id: "butterfly",
    name: "blue morpho",
    latin: "Morpho peleides",
    size: 26,
    gait: "fly",
    lives: "rainforests of central and south america",
    eats: "juice from rotting fruit",
    fact: "the blue isn't pigment: tiny scales on the wings reflect light to make it. butterflies taste with their feet.",
  },
  {
    id: "lady-beetle",
    name: "seven-spot ladybird",
    latin: "Coccinella septempunctata",
    size: 20,
    gait: "fly",
    lives: "gardens and fields across europe, asia and north america",
    eats: "aphids",
    fact: "one ladybird can eat about 5,000 aphids in its lifetime.",
  },
  {
    id: "eagle",
    name: "bald eagle",
    latin: "Haliaeetus leucocephalus",
    size: 40,
    gait: "fly",
    lives: "lakes, rivers and coasts across north america",
    eats: "mostly fish, plus small animals and carrion",
    fact: "pairs add to the same nest year after year. some nests have weighed more than a tonne.",
  },
  {
    id: "bird",
    name: "mountain bluebird",
    latin: "Sialia currucoides",
    size: 26,
    gait: "fly",
    lives: "open country in western north america",
    eats: "insects, plus berries in winter",
    fact: "it hovers in mid-air above the grass, then drops onto the insects it spots.",
  },
  {
    id: "black-bird",
    name: "common raven",
    latin: "Corvus corax",
    size: 30,
    gait: "fly",
    lives: "across the northern hemisphere, from deserts to the arctic",
    eats: "almost anything: carrion, insects, seeds and eggs",
    fact: "ravens solve puzzles, plan ahead, and copy sounds, including human words.",
  },
  {
    id: "beetle",
    name: "rose chafer",
    latin: "Cetonia aurata",
    size: 20,
    gait: "fly",
    lives: "gardens and meadows across europe",
    eats: "flowers, pollen and nectar",
    fact: "unlike most beetles, it flies with its hard wing cases shut, slipping its wings out from the sides.",
  },
  {
    id: "fly",
    name: "housefly",
    latin: "Musca domestica",
    size: 18,
    gait: "fly",
    lives: "anywhere people live",
    eats: "liquids. it spits on food to dissolve it first",
    fact: "its wings beat around 200 times a second.",
  },
];
